Repository TAVE-balak/OTTify-backend, pull requests merged in 2024-03, with the labels that each got.

#157 Feature/#152 discussion
  build.gradle
  src/main/java/tavebalak/OTTify/common/config/RedissonConfig.java
  src/main/java/tavebalak/OTTify/common/lock/AopForTransaction.java
  src/main/java/tavebalak/OTTify/common/lock/CustomSpringELParser.java
  src/main/java/tavebalak/OTTify/common/lock/DistributeLock.java
  src/main/java/tavebalak/OTTify/common/lock/DistributeLockAop.java
  src/main/java/tavebalak/OTTify/community/controller/CommunityController.java
  src/main/java/tavebalak/OTTify/community/repository/CommunityRepository.java
  src/main/java/tavebalak/OTTify/community/service/CommunityService.java
  src/main/java/tavebalak/OTTify/community/service/CommunityServiceImpl.java
  src/main/java/tavebalak/OTTify/error/ErrorCode.java
  src/main/java/tavebalak/OTTify/error/RestExceptionHandler.java
  src/main/java/tavebalak/OTTify/error/exception/InterruptedException.java
  src/test/java/tavebalak/OTTify/community/controller/CommunityControllerTest.java
  src/test/java/tavebalak/OTTify/community/service/CommunityServiceTest.java
  src/test/java/tavebalak/OTTify/community/service/RedissonLockTest.java
  src/test/java/tavebalak/OTTify/review/controller/ReviewMainControllerTest.java
  src/test/java/tavebalak/OTTify/review/repository/ReviewRepositoryTest.java
  src/test/java/tavebalak/OTTify/review/service/ReviewServiceImplTest.java
Labels: ♻️ refactor

#161 Refactor : yml 경로에 맞게 config경로 수정(#160)
  src/main/java/tavebalak/OTTify/common/config/RedissonConfig.java
Labels: 🐛 bug, 📝 documentation

#159 Feature/#158 discussion
  src/main/java/tavebalak/OTTify/community/controller/CommunityController.java
  src/main/java/tavebalak/OTTify/community/service/CommunityService.java
  src/main/java/tavebalak/OTTify/community/service/CommunityServiceImpl.java
  src/main/java/tavebalak/OTTify/program/service/ProgramServiceImpl.java
  src/main/java/tavebalak/OTTify/review/controller/ReviewMainController.java
  src/main/java/tavebalak/OTTify/review/service/ReviewService.java
  src/main/java/tavebalak/OTTify/review/service/ReviewServiceImpl.java
  src/test/java/tavebalak/OTTify/community/controller/CommunityControllerTest.java
  src/test/java/tavebalak/OTTify/community/service/CommunityServiceTest.java
  src/test/java/tavebalak/OTTify/community/service/RedissonLockTest.java
Labels: ♻️ refactor

#165 Refactor/#164 review like count redisson
  src/main/java/tavebalak/OTTify/review/service/ReviewCUDServiceImpl.java
  src/test/java/tavebalak/OTTify/review/service/ReviewRedissonLockTest.java
Labels: ♻️ refactor

#167 Fix: Cors 경로 Origin 추가 (#166)
  src/main/java/tavebalak/OTTify/common/config/WebConfig.java
Labels: 🐛 bug
