Repository TAVE-balak/OTTify-backend, pull requests merged in 2024-01, with the labels that each got.

#29 Feature/#7 logout withdrawal
  src/main/java/tavebalak/OTTify/OtTifyApplication.java
  src/main/java/tavebalak/OTTify/common/config/RedisConfig.java
  src/main/java/tavebalak/OTTify/common/config/SecurityConfig.java
  src/main/java/tavebalak/OTTify/common/constant/GradeType.java
  src/main/java/tavebalak/OTTify/common/constant/Role.java
  src/main/java/tavebalak/OTTify/common/constant/SocialType.java
  src/main/java/tavebalak/OTTify/common/entity/BaseEntity.java
  src/main/java/tavebalak/OTTify/error/ErrorCode.java
  src/main/java/tavebalak/OTTify/error/RestExceptionHandler.java
  src/main/java/tavebalak/OTTify/genre/entity/UserGenre.java
  src/main/java/tavebalak/OTTify/genre/repository/UserGenreRepository.java
  src/main/java/tavebalak/OTTify/genre/service/GenreService.java
  src/main/java/tavebalak/OTTify/oauth/CustomOAuth2User.java
  src/main/java/tavebalak/OTTify/oauth/OAuthAttributes.java
  src/main/java/tavebalak/OTTify/oauth/controller/AuthController.java
  src/main/java/tavebalak/OTTify/oauth/dto/SignUpInfoDto.java
  src/main/java/tavebalak/OTTify/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/tavebalak/OTTify/oauth/jwt/JwtAuthFilter.java
  src/main/java/tavebalak/OTTify/oauth/jwt/JwtService.java
  src/main/java/tavebalak/OTTify/oauth/redis/RefreshToken.java
  src/main/java/tavebalak/OTTify/oauth/redis/RefreshTokenRepository.java
  src/main/java/tavebalak/OTTify/oauth/redis/RefreshTokenService.java
  src/main/java/tavebalak/OTTify/oauth/service/CustomOAuth2UserService.java
  src/main/java/tavebalak/OTTify/oauth/service/OauthService.java
  src/main/java/tavebalak/OTTify/program/entity/Ott.java
  src/main/java/tavebalak/OTTify/program/repository/OttRepository.java
  src/main/java/tavebalak/OTTify/user/entity/RoleType.java
  src/main/java/tavebalak/OTTify/user/entity/SocialType.java
  src/main/java/tavebalak/OTTify/user/entity/User.java
  src/main/java/tavebalak/OTTify/user/entity/UserSubscribingOTT.java
  src/main/java/tavebalak/OTTify/user/repository/UserRepository.java
  src/main/java/tavebalak/OTTify/user/repository/UserSubscribingOTTRepository.java
Labels: 💫 feature

#38 Feature/#8 user profile
  .DS_Store
  .gitignore
  .idea/compiler.xml
  build.gradle
  gradle/.DS_Store
  src/.DS_Store
  src/main/java/tavebalak/OTTify/community/controller/CommunityController.java
  src/main/java/tavebalak/OTTify/community/service/CommunityService.java
  src/main/java/tavebalak/OTTify/community/service/CommunityServiceImpl.java
  src/main/java/tavebalak/OTTify/community/service/ReplyService.java
  src/main/java/tavebalak/OTTify/community/service/ReplyServiceImpl.java
  src/main/java/tavebalak/OTTify/error/ErrorCode.java
  src/main/java/tavebalak/OTTify/error/RestExceptionHandler.java
  src/main/java/tavebalak/OTTify/exception/NotFoundException.java
  src/main/java/tavebalak/OTTify/genre/dto/GenreDTO.java
  src/main/java/tavebalak/OTTify/genre/repository/UserGenreRepository.java
  src/main/java/tavebalak/OTTify/oauth/service/OauthService.java
  src/main/java/tavebalak/OTTify/program/entity/Ott.java
  src/main/java/tavebalak/OTTify/program/repository/OttRepository.java
  src/main/java/tavebalak/OTTify/review/dto/UserReviewRatingListDTO.java
  src/main/java/tavebalak/OTTify/review/entity/Review.java
  src/main/java/tavebalak/OTTify/review/entity/ReviewReviewTag.java
  src/main/java/tavebalak/OTTify/review/repository/ReviewRepository.java
  src/main/java/tavebalak/OTTify/user/controller/UserController.java
  src/main/java/tavebalak/OTTify/user/dto/Request/UserOttUpdateDTO.java
  src/main/java/tavebalak/OTTify/user/dto/Request/UserProfileUpdateDTO.java
  src/main/java/tavebalak/OTTify/user/dto/Response/LikedProgramDTO.java
  src/main/java/tavebalak/OTTify/user/dto/Response/LikedProgramListDTO.java
  src/main/java/tavebalak/OTTify/user/dto/Response/UninterestedProgramDTO.java
  src/main/java/tavebalak/OTTify/user/dto/Response/UninterestedProgramListDTO.java
  src/main/java/tavebalak/OTTify/user/dto/Response/UserOttDTO.java
  src/main/java/tavebalak/OTTify/user/dto/Response/UserOttListDTO.java
  src/main/java/tavebalak/OTTify/user/dto/Response/UserProfileDTO.java
  src/main/java/tavebalak/OTTify/user/entity/User.java
  src/main/java/tavebalak/OTTify/user/repository/LikedProgramRepository.java
  src/main/java/tavebalak/OTTify/user/repository/UninterestedProgramRepository.java
  src/main/java/tavebalak/OTTify/user/repository/UserRepository.java
  src/main/java/tavebalak/OTTify/user/repository/UserSubscribingOTTRepository.java
  src/main/java/tavebalak/OTTify/user/repository/UserSubscribingOttRepository.java
  src/main/java/tavebalak/OTTify/user/service/UserService.java
  src/main/java/tavebalak/OTTify/user/service/UserServiceImpl.java
  src/test/.DS_Store
  src/test/java/.DS_Store
  src/test/java/tavebalak/.DS_Store
Labels: 💫 feature

#39 Feature/#36 program details related entity
  src/main/java/tavebalak/OTTify/common/component/OpenApiDataLoader.java
  src/main/java/tavebalak/OTTify/error/ErrorCode.java
  src/main/java/tavebalak/OTTify/error/reviewCheck/RatingCheckValidator.java
  src/main/java/tavebalak/OTTify/error/reviewCheck/ReviewRatingCheck.java
  src/main/java/tavebalak/OTTify/genre/repository/UserGenreRepository.java
  src/main/java/tavebalak/OTTify/program/controller/ProgramChoiceController.java
  src/main/java/tavebalak/OTTify/program/entity/Program.java
  src/main/java/tavebalak/OTTify/program/service/ProgramChoiceService.java
  src/main/java/tavebalak/OTTify/program/service/ProgramChoiceServiceImpl.java
  src/main/java/tavebalak/OTTify/review/controller/ReviewCUDController.java
  src/main/java/tavebalak/OTTify/review/controller/ReviewShowProgramDetailController.java
  src/main/java/tavebalak/OTTify/review/controller/ReviewTagController.java
  src/main/java/tavebalak/OTTify/review/dto/reviewrequest/ReviewSaveDto.java
  src/main/java/tavebalak/OTTify/review/dto/reviewrequest/ReviewTagIdDto.java
  src/main/java/tavebalak/OTTify/review/dto/reviewrequest/ReviewUpdateDto.java
  src/main/java/tavebalak/OTTify/review/dto/reviewresponse/ReviewProgramResponseDto.java
  src/main/java/tavebalak/OTTify/review/dto/reviewresponse/ReviewResponseDtoList.java
  src/main/java/tavebalak/OTTify/review/dto/reviewtagRequest/ReviewSaveTagDto.java
  src/main/java/tavebalak/OTTify/review/dto/reviewtagResponse/ReviewTagInfo.java
  src/main/java/tavebalak/OTTify/review/dto/reviewtagResponse/ReviewTagListResponseDto.java
  src/main/java/tavebalak/OTTify/review/entity/Review.java
  src/main/java/tavebalak/OTTify/review/entity/ReviewReviewTag.java
  src/main/java/tavebalak/OTTify/review/entity/ReviewTag.java
  src/main/java/tavebalak/OTTify/review/repository/ReviewRepository.java
  src/main/java/tavebalak/OTTify/review/repository/ReviewReviewTagRepository.java
  src/main/java/tavebalak/OTTify/review/repository/ReviewTagRepository.java
  src/main/java/tavebalak/OTTify/review/service/ReviewCUDService.java
  src/main/java/tavebalak/OTTify/review/service/ReviewCUDServiceImpl.java
  src/main/java/tavebalak/OTTify/review/service/ReviewShowProgramDetailService.java
  src/main/java/tavebalak/OTTify/review/service/ReviewShowProgramDetailServiceImpl.java
  src/main/java/tavebalak/OTTify/review/service/ReviewTagService.java
  src/main/java/tavebalak/OTTify/review/service/ReviewTagServiceImpl.java
  src/main/java/tavebalak/OTTify/user/entity/LikedReview.java
  src/main/java/tavebalak/OTTify/user/entity/UninterestedProgram.java
  src/main/java/tavebalak/OTTify/user/entity/User.java
  src/main/java/tavebalak/OTTify/user/repository/LikedProgramRepository.java
  src/main/java/tavebalak/OTTify/user/repository/LikedReviewRepository.java
  src/main/java/tavebalak/OTTify/user/repository/UninterestedProgramRepository.java
  src/test/java/tavebalak/OTTify/community/controller/CommunityControllerTest.java
  src/test/java/tavebalak/OTTify/community/service/CommunityServiceTest.java
  src/test/java/tavebalak/OTTify/review/ReviewShowProgramDetailServiceImplTest.java
Labels: 💫 feature

#45 Submodules 관련 설정
  build.gradle
Labels: 🗃️ infra

#46 Submodules 관련 설정 경로 변경
  build.gradle
Labels: 🗃️ infra

#47 Submodules 관련 설정 경로 변경
  build.gradle
Labels: 🗃️ infra

#52 Setting: CI CD 관련 세팅 (#51)
  .github/workflows/deploy.yml
  appspec.yml
  scripts/deploy.sh
Labels: 🗃️ infra

#40 Feature/#21 user genre
  src/main/java/tavebalak/OTTify/error/ErrorCode.java
  src/main/java/tavebalak/OTTify/genre/dto/request/GenreUpdateDTO.java
  src/main/java/tavebalak/OTTify/genre/entity/UserGenre.java
  src/main/java/tavebalak/OTTify/genre/repository/UserGenreRepository.java
  src/main/java/tavebalak/OTTify/user/controller/UserController.java
  src/main/java/tavebalak/OTTify/user/repository/UserRepository.java
  src/main/java/tavebalak/OTTify/user/service/UserService.java
  src/main/java/tavebalak/OTTify/user/service/UserServiceImpl.java
Labels: 💫 feature

#56 Feature/#23 user activity
  src/main/java/tavebalak/OTTify/community/dto/response/MyDiscussionDto.java
  src/main/java/tavebalak/OTTify/community/entity/Community.java
  src/main/java/tavebalak/OTTify/community/entity/Reply.java
  src/main/java/tavebalak/OTTify/community/repository/CommunityRepository.java
  src/main/java/tavebalak/OTTify/community/repository/ReplyRepository.java
  src/main/java/tavebalak/OTTify/genre/repository/UserGenreRepository.java
  src/main/java/tavebalak/OTTify/review/dto/response/MyReviewDto.java
  src/main/java/tavebalak/OTTify/review/entity/Review.java
  src/main/java/tavebalak/OTTify/review/repository/ReviewRepository.java
  src/main/java/tavebalak/OTTify/review/repository/ReviewReviewTagRepository.java
  src/main/java/tavebalak/OTTify/user/controller/UserController.java
  src/main/java/tavebalak/OTTify/user/entity/LikedCommunity.java
  src/main/java/tavebalak/OTTify/user/entity/LikedReply.java
  src/main/java/tavebalak/OTTify/user/repository/LikedCommunityRepository.java
  src/main/java/tavebalak/OTTify/user/repository/LikedReplyRepository.java
  src/main/java/tavebalak/OTTify/user/repository/LikedReviewRepository.java
  src/main/java/tavebalak/OTTify/user/service/UserService.java
  src/main/java/tavebalak/OTTify/user/service/UserServiceImpl.java
Labels: 💫 feature

#68 Feature/#55 토론페이지 API 수정
  src/main/java/tavebalak/OTTify/community/controller/CommunityController.java
  src/main/java/tavebalak/OTTify/community/dto/request/CommunitySubjectCreateDTO.java
  src/main/java/tavebalak/OTTify/community/dto/request/CommunitySubjectEditDTO.java
  src/main/java/tavebalak/OTTify/community/dto/response/CommunityAriclesDTO.java
  src/main/java/tavebalak/OTTify/community/dto/response/CommunitySubjectEditorDTO.java
  src/main/java/tavebalak/OTTify/community/entity/Community.java
  src/main/java/tavebalak/OTTify/community/service/CommunityService.java
  src/main/java/tavebalak/OTTify/community/service/CommunityServiceImpl.java
  src/main/java/tavebalak/OTTify/error/ErrorCode.java
  src/main/java/tavebalak/OTTify/program/dto/response/ServiceListsDTO.java
  src/main/java/tavebalak/OTTify/program/service/ProgramServiceImpl.java
  src/main/java/tavebalak/OTTify/user/entity/LikedCommunity.java
  src/test/java/tavebalak/OTTify/community/controller/CommunityControllerTest.java
  src/test/java/tavebalak/OTTify/community/service/CommunityServiceTest.java
Labels: 🐛 bug, ♻️ refactor

#69 Feature/#41 program details
  src/main/java/tavebalak/OTTify/program/controller/ProgramDetailsController.java
  src/main/java/tavebalak/OTTify/program/dto/programDetails/Response/ProgramDetailResponse.java
  src/main/java/tavebalak/OTTify/program/dto/programDetails/Response/ProgramResponseDto.java
  src/main/java/tavebalak/OTTify/program/dto/programDetails/openApiRequest/personDetails/Cast.java
  src/main/java/tavebalak/OTTify/program/dto/programDetails/openApiRequest/personDetails/OAProgramCreditsDto.java
  src/main/java/tavebalak/OTTify/program/dto/programDetails/openApiRequest/programDetailRequest/OAMovieDetailsDto.java
  src/main/java/tavebalak/OTTify/program/dto/programDetails/openApiRequest/programDetailRequest/OAProductionCountry.java
  src/main/java/tavebalak/OTTify/program/dto/programDetails/openApiRequest/programDetailRequest/OAProgramDetailsDto.java
  src/main/java/tavebalak/OTTify/program/dto/programDetails/openApiRequest/programDetailRequest/OATvDetailsDto.java
  src/main/java/tavebalak/OTTify/program/dto/programDetails/openApiRequest/programDetailRequest/TmDbGenreInfo.java
  src/main/java/tavebalak/OTTify/program/dto/programDetails/openApiRequest/providerDetails/OACountryDetailsDto.java
  src/main/java/tavebalak/OTTify/program/dto/programDetails/openApiRequest/providerDetails/OAProgramProviderDto.java
  src/main/java/tavebalak/OTTify/program/dto/programDetails/openApiRequest/providerDetails/OAProviderDetailsDto.java
  src/main/java/tavebalak/OTTify/program/service/ProgramDetailsShowService.java
  src/main/java/tavebalak/OTTify/program/service/ProgramDetailsShowServiceImpl.java
Labels: 💫 feature

#71 Bug: 로그인/회원가입 시 응답 url에 userId 추가 (#70)
  src/main/java/tavebalak/OTTify/oauth/CustomOAuth2User.java
  src/main/java/tavebalak/OTTify/oauth/handler/OAuth2AuthenticationSuccessHandler.java
  src/main/java/tavebalak/OTTify/oauth/service/CustomOAuth2UserService.java
Labels: 🐛 bug

#81 Fix: cors 도메인 및 메서드 추가 (#80)
  src/main/java/tavebalak/OTTify/common/config/WebConfig.java
Labels: 🐛 bug

#82 Fix: allowed origin 및 메서드 수정 (#80)
  src/main/java/tavebalak/OTTify/common/config/WebConfig.java
Labels: 🐛 bug

#73 Bug : @PathParam으로 잘못 사용된 어노테이션 변경(#72)
  src/main/java/tavebalak/OTTify/community/controller/CommunityController.java
  src/main/java/tavebalak/OTTify/review/controller/ReviewMainController.java
  src/main/java/tavebalak/OTTify/review/service/ReviewServiceImpl.java
Labels: 🐛 bug

#86 Refactor/#85 swagger @ApiImplicitParam refactor
  src/main/java/tavebalak/OTTify/community/controller/CommunityController.java
  src/main/java/tavebalak/OTTify/genre/repository/UserGenreRepository.java
  src/main/java/tavebalak/OTTify/program/repository/ProgramRepository.java
  src/main/java/tavebalak/OTTify/program/service/ProgramServiceImpl.java
  src/main/java/tavebalak/OTTify/review/controller/ReviewMainController.java
  src/main/java/tavebalak/OTTify/review/service/ReviewServiceImpl.java
Labels: 📝 documentation, ♻️ refactor

#84 Refactor/#79 programdetail ottcast refactor
  src/main/java/tavebalak/OTTify/program/dto/programDetails/openApiRequest/personDetails/Cast.java
  src/main/java/tavebalak/OTTify/program/dto/programDetails/openApiRequest/personDetails/OAProgramCreditsDto.java
  src/main/java/tavebalak/OTTify/program/dto/programDetails/openApiRequest/providerDetails/OACountryDetailsDto.java
  src/main/java/tavebalak/OTTify/program/dto/programDetails/openApiRequest/providerDetails/OAProviderDetailsDto.java
  src/main/java/tavebalak/OTTify/program/service/ProgramDetailsShowServiceImpl.java
Labels: ♻️ refactor

#88 Feat: 저장된 장르 리스트를 보여주기 및 swagger 세팅 (#87)
  src/main/java/tavebalak/OTTify/genre/controller/GenreShowSavedController.java
  src/main/java/tavebalak/OTTify/genre/dto/response/GenreShowSavedDto.java
  src/main/java/tavebalak/OTTify/genre/dto/response/GenreShowSavedListDto.java
  src/main/java/tavebalak/OTTify/genre/service/GenreShowSavedService.java
Labels: 📝 documentation, 💫 feature

#89 Refactor: 구독 중인 OTT 수정 DTO 구조 변경 (#83)
  src/main/java/tavebalak/OTTify/user/controller/UserController.java
  src/main/java/tavebalak/OTTify/user/dto/Request/UserOttUpdateDTO.java
  src/main/java/tavebalak/OTTify/user/service/UserService.java
  src/main/java/tavebalak/OTTify/user/service/UserServiceImpl.java
Labels: ♻️ refactor

#94 Refactor : 추천 프로그램에서 평균 별점 제거, 장르 리스트 반환(#93)
  src/main/java/tavebalak/OTTify/community/dto/request/CommunitySubjectEditDTO.java
  src/main/java/tavebalak/OTTify/community/service/CommunityServiceImpl.java
  src/main/java/tavebalak/OTTify/program/dto/response/ServiceListsDTO.java
  src/main/java/tavebalak/OTTify/program/service/ProgramService.java
  src/main/java/tavebalak/OTTify/program/service/ProgramServiceImpl.java
  src/main/java/tavebalak/OTTify/review/controller/ReviewMainController.java
  src/test/java/tavebalak/OTTify/community/controller/CommunityControllerTest.java
Labels: ♻️ refactor

#97 Refactor: 엑세스 토큰을 통해 가져온 유저가 없을 경우 Notfound->Unauthorized로 변경 (#91)
  src/main/java/tavebalak/OTTify/program/controller/ProgramChoiceController.java
  src/main/java/tavebalak/OTTify/review/controller/ReviewCUDController.java
  src/main/java/tavebalak/OTTify/review/controller/ReviewShowProgramDetailController.java
Labels: ♻️ refactor

#92 Refactor/#90 change reviewtagdto
  src/main/java/tavebalak/OTTify/review/dto/reviewrequest/ReviewSaveDto.java
  src/main/java/tavebalak/OTTify/review/dto/reviewrequest/ReviewTagIdDto.java
  src/main/java/tavebalak/OTTify/review/dto/reviewrequest/ReviewUpdateDto.java
  src/main/java/tavebalak/OTTify/review/service/ReviewCUDServiceImpl.java
  src/test/java/tavebalak/OTTify/review/ReviewShowProgramDetailServiceImplTest.java
Labels: ♻️ refactor

#100 Refactor/#98 show4 review
  src/main/java/tavebalak/OTTify/review/controller/ReviewShowProgramDetailController.java
  src/main/java/tavebalak/OTTify/review/repository/ReviewRepository.java
  src/main/java/tavebalak/OTTify/review/service/ReviewShowProgramDetailService.java
  src/main/java/tavebalak/OTTify/review/service/ReviewShowProgramDetailServiceImpl.java
Labels: 💫 feature, ♻️ refactor

#101 Feature/#99 ott
  .DS_Store
  src/main/java/tavebalak/OTTify/genre/controller/GenreShowSavedController.java
  src/main/java/tavebalak/OTTify/genre/dto/GenreDTO.java
  src/main/java/tavebalak/OTTify/program/controller/OttSavedController.java
  src/main/java/tavebalak/OTTify/program/dto/response/OttDTO.java
  src/main/java/tavebalak/OTTify/program/dto/response/OttListDTO.java
  src/main/java/tavebalak/OTTify/program/service/OttService.java
  src/main/java/tavebalak/OTTify/program/service/OttServiceImpl.java
  src/main/java/tavebalak/OTTify/review/dto/UserReviewRatingListDTO.java
  src/main/java/tavebalak/OTTify/review/repository/ReviewRepository.java
  src/main/java/tavebalak/OTTify/user/controller/UserController.java
  src/main/java/tavebalak/OTTify/user/dto/Request/UserOttUpdateDTO.java
  src/main/java/tavebalak/OTTify/user/dto/Request/UserProfileUpdateDTO.java
  src/main/java/tavebalak/OTTify/user/dto/Response/LikedProgramDTO.java
  src/main/java/tavebalak/OTTify/user/dto/Response/LikedProgramListDTO.java
  src/main/java/tavebalak/OTTify/user/dto/Response/UninterestedProgramDTO.java
  src/main/java/tavebalak/OTTify/user/dto/Response/UninterestedProgramListDTO.java
  src/main/java/tavebalak/OTTify/user/dto/Response/UserOttDTO.java
  src/main/java/tavebalak/OTTify/user/dto/Response/UserOttListDTO.java
  src/main/java/tavebalak/OTTify/user/dto/Response/UserProfileDTO.java
  src/main/java/tavebalak/OTTify/user/entity/UninterestedProgram.java
  src/main/java/tavebalak/OTTify/user/entity/User.java
  src/main/java/tavebalak/OTTify/user/repository/LikedCommunityRepository.java
  src/main/java/tavebalak/OTTify/user/repository/LikedProgramRepository.java
  src/main/java/tavebalak/OTTify/user/repository/LikedReplyRepository.java
  src/main/java/tavebalak/OTTify/user/repository/LikedReviewRepository.java
  src/main/java/tavebalak/OTTify/user/repository/UninterestedProgramRepository.java
  src/main/java/tavebalak/OTTify/user/repository/UserRepository.java
  src/main/java/tavebalak/OTTify/user/repository/UserSubscribingOttRepository.java
  src/main/java/tavebalak/OTTify/user/service/UserServiceImpl.java
Labels: 📝 documentation, 💫 feature

#103 Bug : userGenre Id값이 아닌 GenreId 값으로 장르 레포지토리 조회하도록 변경(#102)
  src/main/java/tavebalak/OTTify/program/service/ProgramServiceImpl.java
Labels: 🐛 bug

#105 Feat: Ott 테이블에 tmdbproviderId 필드 추가 (#104)
  src/main/java/tavebalak/OTTify/program/entity/Ott.java
Labels: 💫 feature

#108 Refactor: ott 이름을 한글로 변환 수정 및 그에 따른 설계 변화 (#106)
  src/main/java/tavebalak/OTTify/program/dto/programDetails/Response/ProgramProviderListResponseDto.java
  src/main/java/tavebalak/OTTify/program/dto/programDetails/Response/ProgramProviderResponseDto.java
  src/main/java/tavebalak/OTTify/program/dto/programDetails/Response/ProgramResponseDto.java
  src/main/java/tavebalak/OTTify/program/dto/programDetails/openApiRequest/providerDetails/OAProviderDetailsDto.java
  src/main/java/tavebalak/OTTify/program/repository/OttRepository.java
  src/main/java/tavebalak/OTTify/program/service/ProgramDetailsShowServiceImpl.java
Labels: 💫 feature, ♻️ refactor

#112 Refactor/#111 update review dto
  src/main/java/tavebalak/OTTify/program/controller/ProgramChoiceController.java
  src/main/java/tavebalak/OTTify/program/controller/ProgramDetailsController.java
  src/main/java/tavebalak/OTTify/program/dto/response/UserSpecificRatingResponseDto.java
  src/main/java/tavebalak/OTTify/program/service/ProgramDetailsShowService.java
  src/main/java/tavebalak/OTTify/program/service/ProgramDetailsShowServiceImpl.java
  src/main/java/tavebalak/OTTify/review/controller/ReviewShowProgramDetailController.java
  src/main/java/tavebalak/OTTify/review/dto/reviewresponse/FourReviewResponseWithCounts.java
  src/main/java/tavebalak/OTTify/review/repository/ReviewRepository.java
  src/main/java/tavebalak/OTTify/review/service/ReviewShowProgramDetailService.java
  src/main/java/tavebalak/OTTify/review/service/ReviewShowProgramDetailServiceImpl.java
  src/test/java/tavebalak/OTTify/review/ReviewShowProgramDetailServiceImplTest.java
Labels: ♻️ refactor

#113 Feature/#110 discussion
  src/main/java/tavebalak/OTTify/community/controller/CommunityController.java
  src/main/java/tavebalak/OTTify/community/dto/request/CommunitySubjectCreateDTO.java
  src/main/java/tavebalak/OTTify/community/dto/request/CommunitySubjectEditDTO.java
  src/main/java/tavebalak/OTTify/community/dto/request/CommunitySubjectImageCreateDTO.java
  src/main/java/tavebalak/OTTify/community/dto/request/CommunitySubjectImageEditDTO.java
  src/main/java/tavebalak/OTTify/community/dto/request/ReplyCommentCreateDTO.java
  src/main/java/tavebalak/OTTify/community/dto/request/ReplyCommentEditDTO.java
  src/main/java/tavebalak/OTTify/community/dto/request/ReplyRecommentCreateDTO.java
  src/main/java/tavebalak/OTTify/community/dto/request/ReplyRecommentEditDTO.java
  src/main/java/tavebalak/OTTify/community/dto/response/CommunityAriclesDTO.java
  src/main/java/tavebalak/OTTify/community/dto/response/CommunitySubjectEditorDTO.java
  src/main/java/tavebalak/OTTify/community/dto/response/CommunitySubjectImageEditorDTO.java
  src/main/java/tavebalak/OTTify/community/dto/response/CommunitySubjectsDTO.java
  src/main/java/tavebalak/OTTify/community/dto/response/CommunitySubjectsListDTO.java
  src/main/java/tavebalak/OTTify/community/entity/Community.java
  src/main/java/tavebalak/OTTify/community/repository/CommunityRepository.java
  src/main/java/tavebalak/OTTify/community/service/CommunityService.java
  src/main/java/tavebalak/OTTify/community/service/CommunityServiceImpl.java
  src/test/java/tavebalak/OTTify/community/repository/CommunityRepositoryTest.java
  src/test/java/tavebalak/OTTify/community/service/CommunityServiceTest.java
Labels: 💫 feature

#116 Refactor/#115 add ott img
  src/main/java/tavebalak/OTTify/program/dto/response/OttDTO.java
  src/main/java/tavebalak/OTTify/program/entity/Ott.java
Labels: ♻️ refactor

#118 Refactor: 프로필 수정 로직 변경
  src/main/java/tavebalak/OTTify/user/controller/UserController.java
  src/main/java/tavebalak/OTTify/user/dto/Request/UserProfileUpdateDTO.java
  src/main/java/tavebalak/OTTify/user/service/UserService.java
  src/main/java/tavebalak/OTTify/user/service/UserServiceImpl.java
Labels: ♻️ refactor

#114 Refactor/#110 discussion
  src/main/java/tavebalak/OTTify/community/controller/CommunityController.java
  src/main/java/tavebalak/OTTify/community/dto/request/CommunitySubjectImageEditDTO.java
  src/main/java/tavebalak/OTTify/community/service/CommunityService.java
  src/main/java/tavebalak/OTTify/community/service/CommunityServiceImpl.java
  src/test/java/tavebalak/OTTify/community/controller/CommunityControllerTest.java
  src/test/java/tavebalak/OTTify/community/service/CommunityServiceTest.java
Labels: ♻️ refactor

#119 Bug /#110 discussion
  src/main/java/tavebalak/OTTify/common/component/MultipartJackson2HttpMessageConverter.java
  src/main/java/tavebalak/OTTify/community/dto/request/CommunitySubjectImageCreateDTO.java
  src/main/java/tavebalak/OTTify/community/dto/request/CommunitySubjectImageEditDTO.java
Labels: 🐛 bug

#123 Feat : 전체조회 DTO에 프로그램명, 토론내용, 댓글수 추가(#122)
  src/main/java/tavebalak/OTTify/community/dto/response/CommunitySubjectsDTO.java
  src/main/java/tavebalak/OTTify/community/repository/ReplyRepository.java
  src/main/java/tavebalak/OTTify/community/service/CommunityServiceImpl.java
  src/main/java/tavebalak/OTTify/review/dto/response/LatestReviewsDTO.java
  src/main/java/tavebalak/OTTify/review/service/ReviewServiceImpl.java
Labels: 💫 feature

#125 Bug : 이미지 수정시 기존 이미지 경로 dto 추가(#124)
  src/main/java/tavebalak/OTTify/common/s3/AWSS3Service.java
  src/main/java/tavebalak/OTTify/community/dto/request/CommunitySubjectEditDTO.java
  src/main/java/tavebalak/OTTify/community/service/CommunityServiceImpl.java
  src/main/java/tavebalak/OTTify/error/ErrorCode.java
Labels: 🐛 bug
