Repository TAVE-balak/OTTify-backend, pull requests merged in 2024-02, with the labels that each got.

#130 Refactor: 프로그램 테이블에 index 설정 추가 (#129)
  src/main/java/tavebalak/OTTify/program/entity/Program.java
Labels: ♻️ refactor

#132 feat : 조회 dto에서 댓글 프로필 사진 추가(#131)
  src/main/java/tavebalak/OTTify/community/dto/response/CommentListsDTO.java
  src/main/java/tavebalak/OTTify/community/service/CommunityServiceImpl.java
Labels: 💫 feature

#134 Refactor/#133 trending program caching
  build.gradle
  src/main/java/tavebalak/OTTify/common/config/CacheConfig.java
  src/main/java/tavebalak/OTTify/common/constant/CacheType.java
  src/main/java/tavebalak/OTTify/program/service/ProgramShowAndSaveServiceImpl.java
Labels: 💫 feature, ♻️ refactor

#139 Refactor/#137 rating
  src/main/java/tavebalak/OTTify/user/dto/Response/UserProfileDTO.java
  src/main/java/tavebalak/OTTify/user/service/UserServiceImpl.java
Labels: ♻️ refactor

#140 Refactor/#136 review nplusone
  src/main/java/tavebalak/OTTify/program/service/ProgramDetailsShowServiceImpl.java
  src/main/java/tavebalak/OTTify/review/repository/ReviewRepository.java
  src/main/java/tavebalak/OTTify/review/service/ReviewShowProgramDetailServiceImpl.java
  src/test/java/tavebalak/OTTify/review/ReviewShowProgramDetailServiceImplTest.java
Labels: ♻️ refactor

#143 Refactor/#138 jpa n+1
  src/main/java/tavebalak/OTTify/community/repository/CommunityRepository.java
  src/main/java/tavebalak/OTTify/community/repository/ReplyRepository.java
  src/main/java/tavebalak/OTTify/review/dto/response/MyReviewDto.java
  src/main/java/tavebalak/OTTify/review/repository/ReviewRepository.java
  src/main/java/tavebalak/OTTify/review/repository/ReviewReviewTagRepository.java
  src/main/java/tavebalak/OTTify/user/repository/LikedReviewRepository.java
  src/main/java/tavebalak/OTTify/user/service/UserServiceImpl.java
Labels: ♻️ refactor

#141 Feature/#135 discussion
  src/main/java/tavebalak/OTTify/common/constant/CacheType.java
  src/main/java/tavebalak/OTTify/community/service/CommunityServiceImpl.java
Labels: ♻️ refactor

#78 Refactor/#77 user by security utils
  src/main/java/tavebalak/OTTify/error/ErrorCode.java
  src/main/java/tavebalak/OTTify/user/controller/UserController.java
  src/main/java/tavebalak/OTTify/user/service/UserService.java
  src/main/java/tavebalak/OTTify/user/service/UserServiceImpl.java
Labels: ♻️ refactor

#147 Refactor/#146 paging dto
  src/main/java/tavebalak/OTTify/user/controller/UserController.java
  src/main/java/tavebalak/OTTify/user/dto/Response/CommunityListWithSliceInfoDTO.java
  src/main/java/tavebalak/OTTify/user/dto/Response/ReviewListWithSliceInfoDTO.java
  src/main/java/tavebalak/OTTify/user/service/UserService.java
  src/main/java/tavebalak/OTTify/user/service/UserServiceImpl.java
Labels: ♻️ refactor

#149 Bug: 대댓글 삭제 API delete 쿼리가 나가지 않는 이슈 해결(#144)
  src/main/java/tavebalak/OTTify/community/controller/CommunityController.java
Labels: 🐛 bug, 📝 documentation

#150 Bug : 대댓글 API 삭제 관련 이슈해결(#144)
  src/main/java/tavebalak/OTTify/community/service/CommunityServiceImpl.java
Labels: 🐛 bug

#151 Refactor: WebClient 를 비동기적으로 활용하여 성능 개선 (#148)
  src/main/java/tavebalak/OTTify/program/service/ProgramDetailsShowServiceImpl.java
Labels: ♻️ refactor

#154 Feature/#142 discussion
  src/main/java/tavebalak/OTTify/community/dto/request/ReplyRecommentCreateDTO.java
  src/main/java/tavebalak/OTTify/community/dto/request/ReplyRecommentEditDTO.java
  src/main/java/tavebalak/OTTify/community/entity/Community.java
  src/main/java/tavebalak/OTTify/community/entity/Reply.java
  src/main/java/tavebalak/OTTify/community/repository/CommunityRepository.java
  src/main/java/tavebalak/OTTify/community/service/CommunityServiceImpl.java
  src/main/java/tavebalak/OTTify/community/service/ReplyServiceImpl.java
  src/main/java/tavebalak/OTTify/error/ErrorCode.java
Labels: ♻️ refactor

#156 Refactor: 데이터 중복 시 예외 처리 (#155)
  src/main/java/tavebalak/OTTify/error/ErrorCode.java
  src/main/java/tavebalak/OTTify/program/service/ProgramShowAndSaveServiceImpl.java
  src/test/java/tavebalak/OTTify/ProgramTest.java
Labels: 🐛 bug
